# Gradle 配置
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric 版本
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# 模组属性
mod_version=1.0.0-26.1.2fabric
maven_group=com.htmlcraft.api

# 依赖版本
fabric_api_version=0.155.2+26.1.2

# 网络超时配置，防止下载依赖卡死
org.gradle.internal.http.socketTimeout=120000
org.gradle.internal.http.connectionTimeout=120000
